version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Although your Flask app does not use MongoDB,
      # the environment variable is provided so that
      # any process or script that requires it can find it.
      - MONGO_URI=mongodb://db:27017/copyright_infringement
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
